//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamikaToysHouse_FrontEnd.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChkLogin", ReplyAction="http://tempuri.org/IService/ChkLoginResponse")]
        bool ChkLogin(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChkLogin", ReplyAction="http://tempuri.org/IService/ChkLoginResponse")]
        System.Threading.Tasks.Task<bool> ChkLoginAsync(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetItem", ReplyAction="http://tempuri.org/IService/GetItemResponse")]
        string[][] GetItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetItem", ReplyAction="http://tempuri.org/IService/GetItemResponse")]
        System.Threading.Tasks.Task<string[][]> GetItemAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ChamikaToysHouse_FrontEnd.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ChamikaToysHouse_FrontEnd.ServiceReference1.IService>, ChamikaToysHouse_FrontEnd.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ChkLogin(string UserName, string Password) {
            return base.Channel.ChkLogin(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<bool> ChkLoginAsync(string UserName, string Password) {
            return base.Channel.ChkLoginAsync(UserName, Password);
        }
        
        public string[][] GetItem() {
            return base.Channel.GetItem();
        }
        
        public System.Threading.Tasks.Task<string[][]> GetItemAsync() {
            return base.Channel.GetItemAsync();
        }
    }
}
